### PR TITLE
app-configs-change

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by pjoshi751 — COMMENTED** [review]
This hardcoding of version - where is this being used.

**Comment by ghost** [comment]
> This hardcoding of version - where is this being used.

It will be used Application Config api to pass the level and language details to  admin-ui.

**Review by pjoshi751 — COMMENTED** [review]
Please remove this from all properities:
`mosipbox.public.url=${mosip_public_url}
`

**Review by pjoshi751 — APPROVED** [review]
Looks fine now.

**Pull request merged**
